site_name: fcount-rs
site_url: https://rnabioco.github.io/fcount-rs
repo_url: https://github.com/rnabioco/fcount-rs
repo_name: rnabioco/fcount-rs

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Examples: examples.md
